version: '3.3'
services:
  db:
    image: mysql:${MYSQL_VERSION:-5.7}
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-iamPassword}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1234}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'   # เข้าใช้งานจาก http://localhost:8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # (ไม่จำเป็น) หากต้องการให้ฟิลด์ล็อกอินถูกกรอกอัตโนมัติ:
      PMA_USER: ${MYSQL_USER:-dbuser}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-iamPassword}
    # (ตัวอย่างเก็บ session ของ phpmyadmin ถ้าต้องการ)
    volumes:
      - /sessions